### ISSUE TITLE
Проблема с конвертацией в data.frame в карте России

### ISSUE THREAD

**Issue by zhitkovk** [akondrashov96/rusmaps#12]
Здравствуйте,

Судя по всему часть полигонов пересекается друг с другом, не давая провести конвертацию.

Команды из ggplot:

`fortify(rus_sub, region = "name")` 

или из пакета broom:

`tidy(rus_sub, region = "name")` 

выдают ошибку:

`Error in get("rgeos", envir = .MAPTOOLS_CACHE) :object 'rgeos' not found`

Подргужаем `rgeos` и `maptools`:

`TopologyException: Input geom 0 is invalid: Self-intersection at or near point 179.99947782174283 65.322178115822794 at 179.99947782174283 65.322178115822794`

[По ссылке](http://gis.stackexchange.com/questions/163445/r-solution-for-topologyexception-input-geom-1-is-invalid-self-intersection-er) есть возможное решение схожей проблемы, которое подойдёт и в этом случае, но, наверное, лучше исправить исходник самой карты.

После устранения проблемы способом выше можно конвертировать spatialPolygon в spatialPolygonDataFrame методом [отсюда](http://gis.stackexchange.com/questions/61633/r-convert-a-spatial-polygon-objet-to-spatial-polygon-data-frame).

**Comment by akondrashov96** [comment]
Здравствуйте,
Да, действительно, в shape-исходнике есть наслоение. Это результат исправления ошибки упрощения границ. Странно, что на других  картах, на которых присутствует ДФО, такая ошибка не возникает, хотя QGIS показывает, что пересечения тоже есть.
Спасибо, что указали на проблему, исправлю в ближайшее время!

**Comment by akondrashov96** [comment]
Исходники исправлены. Команды `fortify` и `tidy` ошибок не выдают.
