### ISSUE TITLE
Проблема с заливкой после "присоединения" кусочка Чукотки

### ISSUE THREAD

**Issue by zhitkovk** [akondrashov96/rusmaps#18]
Здравствуйте,

Из-за особенностей первоначальной карты, после присоединения кусочка Чукотки добавляется лишняя прямая линия. Баг замечен в карте `rus_sub`. В `rus_sub_nc` он не наблюдается.

На картинке:

![map](https://cloud.githubusercontent.com/assets/6890570/17439942/630f1d92-5b3b-11e6-88f2-38761f34675d.png)

**Comment by akondrashov96** [comment]
Здравствуйте!
Да, действительно, в первоначальном shape-файле была небольшая щель между кусочками Чукотки. Теперь лишней линии быть не должно:
![rplot](https://cloud.githubusercontent.com/assets/20055006/17456965/dc71a894-5bf9-11e6-9541-a3126cfdf156.jpeg)
